### ISSUE TITLE
Handler Error on Char Selection

### ISSUE THREAD

**Issue by Dactylr** [OpenNos/OpenNos#1010]
[Handler Error](http://sendvid.com/wypck76e)
the console gives you a error when you send an command like `$CreateItem` or an packet like `preq` on the Char Selection

Console Log:
$CreateItem example:
```
[ERROR] 22:00:29 -- Handler Error SessionId: 10
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenNos.Handler.CommandPacketHandler.CreateItem(String packet) in C:\Users\Dactyl\Source\Repos\OpenNos\OpenNos.Handler\CommandPacketHandler.cs:line 485
   at lambda_method(Closure , Object , String )
   at OpenNos.GameObject.ClientSession.TriggerHandler(String packetHeader, String packet, Boolean force) in C:\Users\Dactyl\Source\Repos\OpenNos\OpenNos.GameObject\Networking\ClientSession.cs:line 440
```
preq example:
```
[ERROR] 22:02:26 -- Handler Error SessionId: 12
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenNos.Handler.BasicPacketHandler.Preq(String packet) in C:\Users\Dactyl\Source\Repos\OpenNos\OpenNos.Handler\BasicPacketHandler.cs:line 834
   at lambda_method(Closure , Object , String )
   at OpenNos.GameObject.ClientSession.TriggerHandler(String packetHeader, String packet, Boolean force) in C:\Users\Dactyl\Source\Repos\OpenNos\OpenNos.GameObject\Networking\ClientSession.cs:line 440
```

PS: nice work guys keep it up :D

**Comment by 0Lucifer0** [comment]
we will need to split CreateCharacter/SelectCharacter/DeleteCharacter into a new Packethandler called CharacterScreenHandler(for example) and block all other packethandler when character not connected

**Comment by chucktheripper** [comment]
Good Idea ;)

**Comment by chucktheripper** [comment]
We need a Flag in ClientSession where we define if a Game has been started already or not. We need to set it in GameStart method, thru this flag we can avoid triggering a wrong handler.

**Comment by 0Lucifer0** [comment]
If character is defined we are in game

**Comment by chucktheripper** [comment]
Exactly
