### ISSUE TITLE
Network dropped, unable to enter game the account number

### ISSUE THREAD

**Issue by ixren** [OpenNos/OpenNos#1040]
System.OverflowException: Value was either too large or too small for an unsigned byte.
   at System.Convert.ToByte(Int32 value)
   at OpenNos.Core.LoginEncryption.Encrypt(String packet) in D:\OpenNos\trunk\OpenNos.Core\LoginEncryption.cs:line 88
   at OpenNos.Core.NetworkClient.SendPacket(String packet) in D:\OpenNos\trunk\OpenNos.Core\Networking\NetworkClient.cs:line 54
   at OpenNos.Handler.LoginPacketHandler.VerifyLogin(String packet) in D:\OpenNos\trunk\OpenNos.Handler\LoginPacketHandler.cs:line 128
   at OpenNos.GameObject.ClientSession.TriggerHandler(String packetHeader, String packet, Boolean force) in D:\OpenNos\trunk\OpenNos.GameObject\Networking\ClientSession.cs:line 465

**Comment by MasterDomino** [comment]
caused by #1039

**Comment by ixren** [comment]
what bug? @MasterDomino
