### ISSUE TITLE
RefreshMail Error, CharacterLifeManager

### ISSUE THREAD

**Issue by Dactylr** [OpenNos/OpenNos#1127]
[RefreshMail Error Vid](http://sendvid.com/aycu0q7e)
After i spammed `pst` this error showed up
Error Log:
```
[ERROR] 00:30:46 -- CharacterLifeManager: Collection was modified; enumeration operation may not execute.
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenNos.GameObject.Character.<RefreshMail>b__383_0(MailDTO s) in C:\Users\Dactyl\Source\Repos\OpenNos\OpenNos.GameObject\Character.cs:line 2017
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at OpenNos.GameObject.Character.RefreshMail() in C:\Users\Dactyl\Source\Repos\OpenNos\OpenNos.GameObject\Character.cs:line 2017
   at OpenNos.GameObject.Map.<>c.<CharacterLifeManager>b__85_1(ClientSession Session) in C:\Users\Dactyl\Source\Repos\OpenNos\OpenNos.GameObject\Map\Map.cs:line 521
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at OpenNos.GameObject.Map.CharacterLifeManager() in C:\Users\Dactyl\Source\Repos\OpenNos\OpenNos.GameObject\Map\Map.cs:line 517
```
this works with the `$Gift` command too 
___
After a relog the outbox displays no messages:
http://i.epvpimg.com/FVFFh.jpg

**Comment by Uppermost** [comment]
this error occur very often (CharacterLifeManager)
