### ISSUE TITLE
get disconnected after use $Mute

### ISSUE THREAD

**Issue by earthnash** [OpenNos/OpenNos#1147]
after use $Mute i get disconnection

2016-10-03 00:36:37,955 [26] ERROR OpenNos.World.Program [(null)] - Handler Error SessionId: 6
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0)
   at OpenNos.Handler.CommandPacketHandler.Mute(String packet) in C:\Users\EQ\Desktop\OpenNos\OpenNos.Handler\CommandPacketHandler.cs:line 896
   at lambda_method(Closure , Object , String )
   at OpenNos.GameObject.ClientSession.TriggerHandler(String packetHeader, String packet, Boolean force) in C:\Users\EQ\Desktop\OpenNos\OpenNos.GameObject\Networking\ClientSession.cs:line 560

**Comment by MasterDomino** [comment]
what did you try to do? we need more info not just short log

**Comment by Uppermost** [comment]
It's impossible to give you more information if it's the community

**Comment by earthnash** [comment]
Reopen please it doesn't fix.
i try with $Mute Someone test
![image](https://cloud.githubusercontent.com/assets/15151087/19031438/6948b594-897e-11e6-90fe-c8b6aca1ef2b.png)

**Comment by MasterDomino** [comment]
tell me how to get it then i will reopen that you must have changed something in db because it doesnt occur for me.
