### ISSUE TITLE
Grid problem

### ISSUE THREAD

**Issue by earthnash** [OpenNos/OpenNos#1148]
2016-10-03 00:50:42,446 [3] ERROR OpenNos.World.Program [(null)] - MonsterLifeManager: Index was outside the bounds of the array.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at EpPathFinding.cs.StaticGrid.GetNodeAt(Int32 iX, Int32 iY)
   at EpPathFinding.cs.JumpPointParam.Reset(GridPos iStartPos, GridPos iEndPos, BaseGrid iSearchGrid)
   at OpenNos.GameObject.Map.JPSPlus(MapCell cell1, MapCell cell2) in C:\Users\EQ\Desktop\OpenNos\OpenNos.GameObject\Map\Map.cs:line 333
   at OpenNos.GameObject.MapMonster.MonsterLife() in C:\Users\EQ\Desktop\OpenNos\OpenNos.GameObject\Map\MapMonster.cs:line 346
   at OpenNos.GameObject.Map.MonsterLifeManager() in C:\Users\EQ\Desktop\OpenNos\OpenNos.GameObject\Map\Map.cs:line 387

**Comment by Martazza** [comment]
How can i reproduce it?

**Comment by Uppermost** [comment]
It's caused by the community we have no idea :(

**Comment by earthnash** [comment]
IDK how to reproduce it
i spam $Summon
but now never happen again
