### ISSUE TITLE
$TeleportToMe * problem

### ISSUE THREAD

**Issue by earthnash** [OpenNos/OpenNos#1149]
after spam $TeleportToMe *  i get disconnection

2016-10-03 00:56:37,464 [22] ERROR OpenNos.World.Program [(null)] - Handler Error SessionId: 38
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenNos.GameObject.ServerManager.ChangeMap(Int64 id) in C:\Users\EQ\Desktop\OpenNos\OpenNos.GameObject\Networking\ServerManager.cs:line 453
   at OpenNos.Handler.CommandPacketHandler.TeleportToMe(String packet) in C:\Users\EQ\Desktop\OpenNos\OpenNos.Handler\CommandPacketHandler.cs:line 1504
   at lambda_method(Closure , Object , String )
   at OpenNos.GameObject.ClientSession.TriggerHandler(String packetHeader, String packet, Boolean force) in C:\Users\EQ\Desktop\OpenNos\OpenNos.GameObject\Networking\ClientSession.cs:line 560

**Comment by chucktheripper** [comment]
duplicate #1141

**Comment by earthnash** [comment]
Sorry my bad😹
