### ISSUE TITLE
Load character issue

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1169]
2016-10-05 15:47:27,587 [16] ERROR OpenNos.World.Program [(null)] - Handler Error SessionId: 4
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenNos.Handler.CommandPacketHandler.Summon(String packet) in C:\Users\root\.jenkins\workspace\OpenNosInstall\OpenNos.Handler\CommandPacketHandler.cs:line 1371
   at lambda_method(Closure , Object , String )
   at OpenNos.GameObject.ClientSession.TriggerHandler(String packetHeader, String packet, Boolean force) in C:\Users\root\.jenkins\workspace\OpenNosInstall\OpenNos.GameObject\Networking\ClientSession.cs:line 571
2016-10-05 15:47:57,743 [16] INFO  OpenNos.World.Program [(null)] - Saving all data!
2016-10-05 15:51:57,743 [14] INFO  OpenNos.World.Program [(null)] - Saving all data!
2016-10-05 15:55:57,743 [14] INFO  OpenNos.World.Program [(null)] - Saving all data!
2016-10-05 15:59:57,743 [7] INFO  OpenNos.World.Program [(null)] - Saving all data!
2016-10-05 16:03:57,759 [7] INFO  OpenNos.World.Program [(null)] - Saving all data!
2016-10-05 16:06:40,165 [10] INFO  OpenNos.World.Program [(null)] - Client connected. ClientId = 3
2016-10-05 16:06:40,181 [14] DEBUG OpenNos.World.Program [(null)] - Client arrived, SessionId: 6
2016-10-05 16:06:40,993 [14] INFO  OpenNos.World.Program [(null)] - Account with SessionId 6 has arrived.
2016-10-05 16:06:41,009 [14] ERROR OpenNos.World.Program [(null)] - Handler Error SessionId: 6
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenNos.Handler.CharacterScreenPacketHandler.LoadCharacters(String packet) in C:\Users\root\.jenkins\workspace\OpenNosInstall\OpenNos.Handler\CharacterScreenPacketHandler.cs:line 355
   at lambda_method(Closure , Object , String )
   at OpenNos.GameObject.ClientSession.TriggerHandler(String packetHeader, String packet, Boolean force) in C:\Users\root\.jenkins\workspace\OpenNosInstall\OpenNos.GameObject\Networking\ClientSession.cs:line 571
2016-10-05 16:06:41,025 [14] INFO  OpenNos.World.Program [(null)] - Client disconnected! ClientId = 3
2016-10-05 16:06:47,618 [10] INFO  OpenNos.World.Program [(null)] - Client connected. ClientId = 4
2016-10-05 16:06:47,634 [7] DEBUG OpenNos.World.Program [(null)] - Client arrived, SessionId: 8
2016-10-05 16:06:48,400 [14] INFO  OpenNos.World.Program [(null)] - Account with SessionId 8 has arrived.
2016-10-05 16:06:48,415 [14] ERROR OpenNos.World.Program [(null)] - Handler Error SessionId: 8
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenNos.Handler.CharacterScreenPacketHandler.LoadCharacters(String packet) in C:\Users\root\.jenkins\workspace\OpenNosInstall\OpenNos.Handler\CharacterScreenPacketHandler.cs:line 355
   at lambda_method(Closure , Object , String )
   at OpenNos.GameObject.ClientSession.TriggerHandler(String packetHeader, String packet, Boolean force) in C:\Users\root\.jenkins\workspace\OpenNosInstall\OpenNos.GameObject\Networking\ClientSession.cs:line 571
2016-10-05 16:06:48,415 [14] INFO  OpenNos.World.Program [(null)] - Client disconnected! ClientId = 4
2016-10-05 16:07:57,764 [7] INFO  OpenNos.World.Program [(null)] - Saving all data!

Caused by $CreateItem 8271 by example the character is impossible to use after that

**Comment by Uppermost** [comment]
Close #1168 Already in issue
