### ISSUE TITLE
Can't use skill skillid 211

### ISSUE THREAD

**Issue by earthnash** [OpenNos/OpenNos#1304]
![image](https://cloud.githubusercontent.com/assets/15151087/19591007/15075ab0-979f-11e6-9cb3-1f3c8d37fa35.png)
after use i get disconnect.
close it if issue opened

**Comment by chucktheripper** [comment]
I think its duplicate with 1298, but the error message is useful ;)

**Comment by earthnash** [comment]
sometime i use $summon and get disconnnect
2016-10-21 15:06:42,198 [38] DEBUG OpenNos.World.Program [(null)] - Session: 36 Method: Summon Packet: 18860 $Summon 443 200 1
2016-10-21 15:06:42,199 [38] ERROR OpenNos.World.Program [(null)] - Handler Error SessionId: 36
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at OpenNos.GameObject.Map.GetNextMonsterId() in C:\Users\EQ\Desktop\OpenNos\OpenNos.GameObject\Map\Map.cs:line 303
   at OpenNos.Handler.CommandPacketHandler.Summon(String packet) in C:\Users\EQ\Desktop\OpenNos\OpenNos.Handler\CommandPacketHandler.cs:line 1393
   at lambda_method(Closure , Object , String )
   at OpenNos.GameObject.ClientSession.TriggerHandler(String packetHeader, String packet, Boolean force) in C:\Users\EQ\Desktop\OpenNos\OpenNos.GameObject\Networking\ClientSession.cs:line 534
2016-10-21 15:06:42,501 [38] INFO  OpenNos.World.Program [(null)] - Client disconnected! ClientId = 18

**Comment by chucktheripper** [comment]
This error is new ;)
