### ISSUE TITLE
Summon Mob on Empty Map

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#1305]
sometime i use $summon and get disconnnect
2016-10-21 15:06:42,198 [38] DEBUG OpenNos.World.Program [(null)] - Session: 36 Method: Summon Packet: 18860 $Summon 443 200 1
2016-10-21 15:06:42,199 [38] ERROR OpenNos.World.Program [(null)] - Handler Error SessionId: 36
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at OpenNos.GameObject.Map.GetNextMonsterId() in C:\Users\EQ\Desktop\OpenNos\OpenNos.GameObject\Map\Map.cs:line 303
   at OpenNos.Handler.CommandPacketHandler.Summon(String packet) in C:\Users\EQ\Desktop\OpenNos\OpenNos.Handler\CommandPacketHandler.cs:line 1393
   at lambda_method(Closure , Object , String )
   at OpenNos.GameObject.ClientSession.TriggerHandler(String packetHeader, String packet, Boolean force) in C:\Users\EQ\Desktop\OpenNos\OpenNos.GameObject\Networking\ClientSession.cs:line 534
2016-10-21 15:06:42,501 [38] INFO  OpenNos.World.Program [(null)] - Client disconnected! ClientId = 18

**Comment by 0Lucifer0** [comment]
It was fixed before ><

**Comment by chucktheripper** [comment]
There was a problem ;)

**Comment by chucktheripper** [comment]
Max causes Enumeration Problems because it needs to check each object with each for the result.

**Comment by 0Lucifer0** [comment]
#1184 so just use last but we need to keep default
