### ISSUE TITLE
ExchangeRequest NullException

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1408]
2016-11-08 23:59:05,069 [147] DEBUG OpenNos.World.Program [(null)] - Session: 380 Method: ExchangeRequest Packet: 51932 req_exc 4
2016-11-08 23:59:05,106 [147] DEBUG OpenNos.World.Program [(null)] - Session: 396 Method: ExchangeRequest Packet: 65431 req_exc 4
2016-11-08 23:59:05,106 [147] ERROR OpenNos.World.Program [(null)] - Handler Error SessionId: 396
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenNos.Handler.InventoryPacketHandler.ExchangeRequest(String deserializedPacket) in C:\Users\root\Documents\GitHub\OpenNos\OpenNos.Handler\InventoryPacketHandler.cs:line 467
   at lambda_method(Closure , Object , Object )
   at OpenNos.GameObject.ClientSession.TriggerHandler(String packetHeader, String packet, Boolean force) in C:\Users\root\Documents\GitHub\OpenNos\OpenNos.GameObject\Networking\ClientSession.cs:line 584

**Comment by chucktheripper** [comment]
Whats Type 4 for Request Exchange?

**Comment by Uppermost** [comment]
Seem's to be cancelled trade.
