### ISSUE TITLE
SystemNullReference req_exc 3

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1416]
2016-11-10 01:23:33,255 [18] DEBUG OpenNos.World.Program [(null)] - Session: 18 Method: ExchangeRequest Packet: 868 req_exc 3
2016-11-10 01:23:33,256 [18] DEBUG OpenNos.World.Program [(null)] - Session: 18 Method: AddToInventory Packet: 2511
2016-11-10 01:23:33,257 [18] DEBUG OpenNos.World.Program [(null)] - Session: 18 Method: AddToInventory Packet: 1363
2016-11-10 01:23:33,258 [18] DEBUG OpenNos.World.Program [(null)] - Session: 18 Method: AddToInventoryWithSlotAndType Packet: Slot: 33 Type: Main VNUM: 1363
2016-11-10 01:23:33,258 [18] DEBUG OpenNos.World.Program [(null)] - Session: 18 Method: AddToInventory Packet: 2282
2016-11-10 01:23:33,259 [18] DEBUG OpenNos.World.Program [(null)] - Session: 18 Method: AddToInventoryWithSlotAndType Packet: Slot: 18 Type: Etc VNUM: 2282
2016-11-10 01:23:33,259 [18] DEBUG OpenNos.World.Program [(null)] - Session: 26 Method: RemoveItemAmountFromInventory Packet: InventoryId: 5b36c478-0bea-4dec-adb6-d5790df01627 amount: 8
2016-11-10 01:23:33,261 [18] DEBUG OpenNos.World.Program [(null)] - Session: 26 Method: RemoveItemAmountFromInventory Packet: InventoryId: efa1fc76-e2f6-4a43-a31f-84ea06fb93ec amount: 2
2016-11-10 01:23:33,262 [18] DEBUG OpenNos.World.Program [(null)] - Session: 26 Method: RemoveItemAmountFromInventory Packet: InventoryId: 71757fd0-02b9-4527-88a3-c5ca20bab68d amount: 35
2016-11-10 01:23:33,263 [18] DEBUG OpenNos.World.Program [(null)] - Session: 18 Method: ExchangeRequest Packet: 869 req_exc 3
2016-11-10 01:23:33,263 [18] ERROR OpenNos.World.Program [(null)] - Handler Error SessionId: 18
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenNos.Handler.InventoryPacketHandler.ExchangeRequest(String deserializedPacket) in C:\Users\root\Documents\GitHub\OpenNos\OpenNos.Handler\InventoryPacketHandler.cs:line 342
   at lambda_method(Closure , Object , Object )
   at OpenNos.GameObject.ClientSession.TriggerHandler(String packetHeader, String packet, Boolean force) in C:\Users\root\Documents\GitHub\OpenNos\OpenNos.GameObject\Networking\ClientSession.cs:line 588

**Comment by chucktheripper** [comment]
Similar to #1408 ?

**Comment by Uppermost** [comment]
exc 4 on 1408 but maybe yes
