### ISSUE TITLE
$ChangeClass 5 kicks from world server

### ISSUE THREAD

**Issue by Martazza** [OpenNos/OpenNos#1542]
`2016-11-20 23:19:07,800 [12] ERROR OpenNos.World.Program [(null)] - Handler Error SessionId: 4
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at OpenNos.GameObject.Character.HPLoad() in C:\Users\Administrator\Source\Repos\OpenNos\OpenNos.GameObject\Character.cs:line 1962
   at OpenNos.GameObject.Character.ChangeClass(ClassType characterClass) in C:\Users\Administrator\Source\Repos\OpenNos\OpenNos.GameObject\Character.cs:line 434
   at OpenNos.Handler.CommandPacketHandler.ChangeClass(ChangeClassPacket changeClassPacket) in C:\Users\Administrator\Source\Repos\OpenNos\OpenNos.Handler\CommandPacketHandler.cs:line 250
   at lambda_method(Closure , Object , Object )
   at OpenNos.GameObject.ClientSession.TriggerHandler(String packetHeader, String packet, Boolean force) in C:\Users\Administrator\Source\Repos\OpenNos\OpenNos.GameObject\Networking\ClientSession.cs:line 592
`

**Comment by Ciapa** [comment]
Future, as this is not an urgent Issue.
