### ISSUE TITLE
Invalid Operation Exception SingleOrDefault

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1630]
2016-11-28 22:21:02,872 [19] ERROR OpenNos.World.Program [(null)] - Handler Error SessionId: 344
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenNos.GameObject.Inventory.LoadBySlotAndType(Int16 slot, InventoryType type) in C:\Users\Kaddo\Source\Repos\OpenNos\OpenNos.GameObject\Inventory.cs:line 316
   at OpenNos.Handler.InventoryPacketHandler.Wear(String packet) in C:\Users\Kaddo\Source\Repos\OpenNos\OpenNos.Handler\InventoryPacketHandler.cs:line 1487
   at lambda_method(Closure , Object , Object )
   at OpenNos.GameObject.ClientSession.TriggerHandler(String packetHeader, String packet, Boolean force) in C:\Users\Kaddo\Source\Repos\OpenNos\OpenNos.GameObject\Networking\ClientSession.cs:line 598
2016-11-28 22:21:56,544 [5] ERROR OpenNos.World.Program [(null)] - Handler Error SessionId: 374
System.InvalidOperationException: Sequence contains more than one matching element

**Comment by MasterDomino** [comment]
someone destroyed the database then, there cant be multiple items on 1 slot
```csharp
            return this.GetAllItems().SingleOrDefault(i => i != null && i.Slot.Equals(slot) && i.Type.Equals(type));
```
