### ISSUE TITLE
LoadBySlot Invalid Operation Exception 

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1633]
2016-11-28 22:51:32,360 [25] ERROR OpenNos.World.Program [(null)] - LoadBySlot: Sequence contains more than one element
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__2[TResult](IEnumerable`1 sequence)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at OpenNos.DAL.EF.CharacterDAO.LoadBySlot(Int64 accountId, Byte slot) in C:\Users\Kaddo\Source\Repos\OpenNos\OpenNos.DAL.EF\CharacterDAO.cs:line 198

**Comment by MasterDomino** [comment]
again looks like killed database, u cant have 2 characters in 1 slot
