### ISSUE TITLE
Error when i parse teleporter

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#357]
![image](https://cloud.githubusercontent.com/assets/15254478/14065074/d3c4c1dc-f41a-11e5-83ab-e4ba426883b9.png)

Problem with teleporter parser

**Comment by Martazza** [comment]
This error is caused by missing maps file..
Extract them from .NOS files

**Comment by Uppermost** [comment]
No is not the problem i have all files

**Comment by MasterDomino** [comment]
like martazza said try to update maps and remove comments from packet.txt
otherwise send us picture when parsing stopped

**Comment by 0Lucifer0** [comment]
Send me the inner exception :)

**Comment by Uppermost** [comment]
This ? 

![image](https://cloud.githubusercontent.com/assets/15254478/14066230/4ff58204-f444-11e5-8ab5-e3087d0cead3.png)


L'exception System.Data.Entity.Infrastructure.DbUpdateException n'a pas été gérée
  HResult=-2146233087
  Message=An error occurred while updating the entries. See the inner exception for details.
  Source=EntityFramework
  StackTrace:
       at System.Data.Entity.Internal.InternalContext.SaveChanges()
       at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
       at System.Data.Entity.DbContext.SaveChanges()
       at OpenNos.DAL.EF.MySQL.TeleporterDAO.Insert(TeleporterDTO teleporter) in C:\Users\Anthonyy\Source\Repos\OpenNos\OpenNos\OpenNos.DAL.EF.MySQL\TeleporterDAO.cs:line 35
       at OpenNos.Import.Console.ImportFactory.ImportTeleporters() in C:\Users\Anthonyy\Source\Repos\OpenNos\OpenNos\OpenNos.Import.Console\ImportFactory.cs:line 445
       at OpenNos.Import.Console.Program.Main(String[] args) in C:\Users\Anthonyy\Source\Repos\OpenNos\OpenNos\OpenNos.Import.Console\Program.cs:line 78
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233087
       Message=An error occurred while updating the entries. See the inner exception for details.
       Source=EntityFramework
       StackTrace:
            at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
            at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
            at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
            at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
            at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
            at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
            at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
            at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
            at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
            at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
            at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
            at System.Data.Entity.Internal.InternalContext.SaveChanges()
       InnerException: 
            ErrorCode=-2147467259
            HResult=-2147467259
            Message=Cannot add or update a child row: a foreign key constraint fails ("opennos"."teleporter", CONSTRAINT "FK_TeleporterMapNpc" FOREIGN KEY ("MapNpcId") REFERENCES "mapnpc" ("MapNpcId") ON DELETE NO ACTION ON UPDATE NO ACTION)
            Number=1452
            Source=MySql.Data
            StackTrace:
                 at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
                 at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
                 at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
                 at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
                 at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
                 at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
                 at MySql.Data.Entity.EFMySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
                 at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
                 at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
                 at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
                 at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
                 at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
                 at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
                 at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
                 at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
            InnerException:
