### ISSUE TITLE
Cross Save for SaveAll

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#607]
Always make sure that the Object that you want to save cannot be modified anymore. For a List for instance, do not iterate thru Character.InventoryList , copy it with ToList in a new list and work with this to avoid exceptions like the one below.

[ERROR] 19:20:18 -- Collection was modified; enumeration operation may not execu

te.

System.InvalidOperationException: Collection was modified; enumeration operation

 may not execute.

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resour

ce)

   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()

   at System.Collections.Generic.List`1.Enumerator.MoveNext()

   at OpenNos.DAL.EF.MySQL.InventoryDAO.InsertOrUpdate(IEnumerable`1 inventories

) in C:\Users\Administrateur\Documents\GitHub\OpenNos\OpenNos.DAL.EF.MySQL\Inven

toryDAO.cs:line 123

**Comment by chucktheripper** [comment]
Maybe also Deep Copy character and save it.

**Comment by chucktheripper** [comment]
This isnt done so far, right?
