### ISSUE TITLE
Exception on the godmod command after change map

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#828]
![image](https://cloud.githubusercontent.com/assets/15254478/17897510/bea5b54a-6954-11e6-83de-081e813af409.png)

L'exception System.NullReferenceException n'a pas été gérée par le code utilisateur
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=OpenNos.GameObject
  StackTrace:
       at OpenNos.GameObject.MapMonster.MonsterLife() in C:\Users\Anthonyy\Source\Repos\OpenNos\OpenNos\OpenNos.GameObject\Map\MapMonster.cs:line 207
       at OpenNos.GameObject.Map.<>c__DisplayClass59_1.<MonsterLifeManager>b__1() in C:\Users\Anthonyy\Source\Repos\OpenNos\OpenNos\OpenNos.GameObject\Map\Map.cs:line 349
       at System.Threading.Tasks.Task.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
  InnerException:

**Comment by Uppermost** [comment]
Why you close it ? I have this error always when i kill monster and change map

**Comment by Uppermost** [comment]
ok
