### ISSUE TITLE
Bug in generateski

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#906]
#Bug in GenerateSki (Martazza report)
2016-09-06 16:03:17,919 [44] ERROR OpenNos.World.Program [(null)] - Handler Error SessionId: 26
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at OpenNos.GameObject.Character.GenerateSki() in C:\Users\Administrator\Desktop\OpenNos\OpenNos.GameObject\Character.cs:line 829

This is the 829 line
```skibase = $"{skill.ElementAt(0).SkillVNum} {skill.ElementAt(0).SkillVNum}";```

**Comment by 0Lucifer0** [comment]
That mean You have 0 skill

**Comment by unknownforces** [comment]
I had this issue too when I was killing in WK, I had skill but it just wouldn't work.

**Comment by 0Lucifer0** [comment]
i don't think so ^^ generateSki is a function in order to show the list of skill it's never called when we use skill

**Comment by 0Lucifer0** [comment]
is this issue still here?
