### ISSUE TITLE
Drop/Inventar Bug

### ISSUE THREAD

**Issue by Dactylr** [OpenNos/OpenNos#965]
[Drop/Inventar Bug](http://sendvid.com/aqn35wmm)
when you drop the items fast enough and pick them up in a loop this error log shows up

```
Handler Error SessionId: 12
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at OpenNos.GameObject.InventoryList.PutItem(Byte type, Int16 slot, Byte amount, Inventory& inv) in C:\Users\Dactyl\Source\Repos\OpenNos\OpenNos.GameObject\InventoryList.cs:line 359
   at OpenNos.Handler.InventoryPacketHandler.PutItem(String packet) in C:\Users\Dactyl\Source\Repos\OpenNos\OpenNos.Handler\InventoryPacketHandler.cs:line 564
   at lambda_method(Closure , Object , String )
   at OpenNos.GameObject.ClientSession.TriggerHandler(String packetHeader, String packet, Boolean force) in C:\Users\Dactyl\Source\Repos\OpenNos\OpenNos.GameObject\Networking\ClientSession.cs:line 401
```

**Comment by chucktheripper** [comment]
sweet, ill have a look at that

**Comment by chucktheripper** [comment]
please reopen ticket if the Problem still exists
